import type { Recipe } from "./types"

export const completeRecipes: Recipe[] = [
  // Easy Recipes (35 recipes)
  {
    id: "1",
    title: "Scrambled Eggs",
    description: "Fluffy and creamy scrambled eggs perfect for breakfast",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=300&fit=crop",
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    difficulty: "Easy",
    ingredients: ["4 eggs", "2 tbsp butter", "1/4 tsp salt", "1/8 tsp pepper", "2 tbsp milk"],
    instructions: [
      "Crack eggs into a bowl and whisk with milk, salt, and pepper",
      "Heat butter in a non-stick pan over medium-low heat",
      "Pour in eggs and let sit for 20 seconds",
      "Gently stir with a spatula, pushing eggs from edges to center",
      "Continue stirring gently until eggs are just set but still creamy",
      "Remove from heat and serve immediately",
    ],
    category: "Breakfast",
    createdAt: "2024-01-01",
  },
  {
    id: "2",
    title: "Pancakes",
    description: "Classic fluffy pancakes that are perfect for weekend mornings",
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=300&fit=crop",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "2 cups all-purpose flour",
      "2 eggs",
      "1 3/4 cups milk",
      "1/4 cup melted butter",
      "2 tbsp sugar",
      "2 tsp baking powder",
    ],
    instructions: [
      "Mix flour, sugar, and baking powder in a large bowl",
      "In another bowl, whisk eggs, milk, and melted butter",
      "Pour wet ingredients into dry ingredients and stir until just combined",
      "Heat a griddle or large pan over medium heat",
      "Pour 1/4 cup batter for each pancake",
      "Cook until bubbles form on surface, then flip and cook until golden",
    ],
    category: "Breakfast",
    createdAt: "2024-01-02",
  },
  {
    id: "3",
    title: "Grilled Cheese",
    description: "Golden crispy grilled cheese sandwich with melted cheese inside",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=300&fit=crop",
    prepTime: 5,
    cookTime: 8,
    servings: 1,
    difficulty: "Easy",
    ingredients: ["2 slices bread", "2 slices cheese", "2 tbsp butter"],
    instructions: [
      "Butter one side of each bread slice",
      "Place cheese between bread slices, buttered sides out",
      "Heat a pan over medium heat",
      "Cook sandwich for 3-4 minutes until golden brown",
      "Flip and cook another 3-4 minutes until other side is golden",
      "Cut diagonally and serve hot",
    ],
    category: "Lunch",
    createdAt: "2024-01-03",
  },
  {
    id: "4",
    title: "Caesar Salad",
    description: "Classic Caesar salad with crisp romaine and homemade dressing",
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "1 head romaine lettuce",
      "1/2 cup croutons",
      "1/4 cup parmesan cheese",
      "2 anchovy fillets",
      "1/4 cup Caesar dressing",
    ],
    instructions: [
      "Wash and chop romaine lettuce into bite-sized pieces",
      "Place lettuce in a large salad bowl",
      "Add croutons and toss gently",
      "Drizzle with Caesar dressing",
      "Top with grated parmesan and anchovy fillets",
      "Toss everything together and serve immediately",
    ],
    category: "Salad",
    createdAt: "2024-01-04",
  },
  {
    id: "5",
    title: "Pasta with Butter",
    description: "Simple buttered pasta with cheese - comfort food at its finest",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400&h=300&fit=crop",
    prepTime: 5,
    cookTime: 12,
    servings: 2,
    difficulty: "Easy",
    ingredients: ["8 oz pasta", "4 tbsp butter", "1/2 cup parmesan cheese", "1/2 tsp salt", "1/4 tsp pepper"],
    instructions: [
      "Cook pasta according to package directions",
      "Reserve 1/2 cup pasta water before draining",
      "Return pasta to pot over low heat",
      "Add butter and toss until melted",
      "Add pasta water gradually until creamy",
      "Stir in parmesan, salt, and pepper",
    ],
    category: "Italian",
    createdAt: "2024-01-05",
  },
  {
    id: "6",
    title: "French Toast",
    description: "Sweet and custardy French toast perfect for special mornings",
    image: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=400&h=300&fit=crop",
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    difficulty: "Easy",
    ingredients: ["8 slices bread", "4 eggs", "1/2 cup milk", "1 tsp cinnamon", "1 tsp vanilla", "2 tbsp butter"],
    instructions: [
      "Whisk eggs, milk, cinnamon, and vanilla in a shallow dish",
      "Heat butter in a large skillet over medium heat",
      "Dip each bread slice in egg mixture, coating both sides",
      "Cook in skillet for 2-3 minutes per side until golden",
      "Serve hot with syrup or powdered sugar",
      "Garnish with fresh berries if desired",
    ],
    category: "Breakfast",
    createdAt: "2024-01-06",
  },
  {
    id: "7",
    title: "Quesadilla",
    description: "Crispy cheese-filled quesadilla with chicken and vegetables",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop",
    prepTime: 10,
    cookTime: 8,
    servings: 2,
    difficulty: "Easy",
    ingredients: [
      "2 large tortillas",
      "1 cup shredded cheese",
      "1/2 cup cooked chicken",
      "1/4 cup diced peppers",
      "1/4 cup diced onions",
    ],
    instructions: [
      "Heat a large skillet over medium heat",
      "Place one tortilla in the skillet",
      "Sprinkle cheese, chicken, peppers, and onions on half the tortilla",
      "Fold tortilla in half and cook for 3-4 minutes",
      "Flip and cook another 3-4 minutes until crispy",
      "Cut into wedges and serve with salsa",
    ],
    category: "Mexican",
    createdAt: "2024-01-07",
  },
  {
    id: "8",
    title: "Smoothie Bowl",
    description: "Healthy and colorful smoothie bowl topped with fresh fruits",
    image: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=400&h=300&fit=crop",
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    difficulty: "Easy",
    ingredients: ["1 frozen banana", "1/2 cup mixed berries", "1/2 cup yogurt", "1/4 cup granola", "1 tbsp honey"],
    instructions: [
      "Blend frozen banana, berries, and yogurt until smooth",
      "Pour into a bowl",
      "Top with granola, fresh berries, and sliced banana",
      "Drizzle with honey",
      "Add any other desired toppings",
      "Serve immediately",
    ],
    category: "Breakfast",
    createdAt: "2024-01-08",
  },
  {
    id: "9",
    title: "Avocado Toast",
    description: "Trendy avocado toast with perfect toppings",
    image: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&h=300&fit=crop",
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    difficulty: "Easy",
    ingredients: [
      "2 slices bread",
      "1 ripe avocado",
      "1 tbsp lemon juice",
      "1/4 tsp salt",
      "1/8 tsp pepper",
      "1 small tomato",
    ],
    instructions: [
      "Toast bread slices until golden brown",
      "Mash avocado with lemon juice, salt, and pepper",
      "Spread avocado mixture on toast",
      "Top with sliced tomato",
      "Season with additional salt and pepper",
      "Serve immediately",
    ],
    category: "Breakfast",
    createdAt: "2024-01-09",
  },
  {
    id: "10",
    title: "Chicken Salad",
    description: "Creamy chicken salad with fruit and nuts",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=300&fit=crop",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "2 cups cooked chicken",
      "1/2 cup mayonnaise",
      "1/4 cup diced celery",
      "1/4 cup grapes",
      "1/4 cup chopped nuts",
      "lettuce leaves",
    ],
    instructions: [
      "Dice cooked chicken into bite-sized pieces",
      "Mix chicken with mayonnaise in a large bowl",
      "Add celery, grapes, and nuts",
      "Season with salt and pepper to taste",
      "Chill for at least 30 minutes",
      "Serve on lettuce leaves or bread",
    ],
    category: "Salad",
    createdAt: "2024-01-10",
  },
  {
    id: "11",
    title: "Tuna Sandwich",
    description: "Classic tuna salad sandwich with fresh vegetables",
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&h=300&fit=crop",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "Easy",
    ingredients: ["1 can tuna", "3 tbsp mayonnaise", "4 slices bread", "2 lettuce leaves", "1 tomato", "1/4 onion"],
    instructions: [
      "Drain tuna and mix with mayonnaise",
      "Toast bread if desired",
      "Spread tuna mixture on two slices of bread",
      "Add lettuce, tomato slices, and onion",
      "Top with remaining bread slices",
      "Cut in half and serve",
    ],
    category: "Lunch",
    createdAt: "2024-01-11",
  },
  {
    id: "12",
    title: "Oatmeal",
    description: "Warm and comforting oatmeal with sweet toppings",
    image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=400&h=300&fit=crop",
    prepTime: 5,
    cookTime: 8,
    servings: 2,
    difficulty: "Easy",
    ingredients: ["1 cup rolled oats", "2 cups milk", "1 banana", "2 tbsp honey", "1/2 tsp cinnamon"],
    instructions: [
      "Bring milk to a simmer in a saucepan",
      "Add oats and cook for 5-7 minutes, stirring occasionally",
      "Stir in cinnamon",
      "Serve in bowls topped with sliced banana",
      "Drizzle with honey",
      "Add any other desired toppings",
    ],
    category: "Breakfast",
    createdAt: "2024-01-12",
  },
  {
    id: "13",
    title: "Caprese Salad",
    description: "Fresh Italian caprese salad with tomatoes and mozzarella",
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop",
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "2 large tomatoes",
      "8 oz fresh mozzarella",
      "1/4 cup fresh basil",
      "3 tbsp olive oil",
      "2 tbsp balsamic vinegar",
    ],
    instructions: [
      "Slice tomatoes and mozzarella into 1/4-inch thick rounds",
      "Arrange alternating slices on a platter",
      "Tuck basil leaves between slices",
      "Drizzle with olive oil and balsamic vinegar",
      "Season with salt and pepper",
      "Let sit for 10 minutes before serving",
    ],
    category: "Salad",
    createdAt: "2024-01-13",
  },
  {
    id: "14",
    title: "Banana Bread",
    description: "Moist and sweet banana bread perfect for any time",
    image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&h=300&fit=crop",
    prepTime: 15,
    cookTime: 60,
    servings: 8,
    difficulty: "Easy",
    ingredients: [
      "3 ripe bananas",
      "2 cups flour",
      "3/4 cup sugar",
      "2 eggs",
      "1/3 cup melted butter",
      "1 tsp baking soda",
    ],
    instructions: [
      "Preheat oven to 350°F and grease a loaf pan",
      "Mash bananas in a large bowl",
      "Mix in melted butter, sugar, and eggs",
      "Add flour and baking soda, stir until just combined",
      "Pour into prepared loaf pan",
      "Bake for 60 minutes until a toothpick comes out clean",
    ],
    category: "Dessert",
    createdAt: "2024-01-14",
  },
  {
    id: "15",
    title: "Chicken Soup",
    description: "Comforting chicken noodle soup perfect for cold days",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    difficulty: "Easy",
    ingredients: [
      "1 lb chicken breast",
      "2 carrots",
      "2 celery stalks",
      "1 onion",
      "8 oz egg noodles",
      "8 cups chicken broth",
    ],
    instructions: [
      "Dice chicken, carrots, celery, and onion",
      "Heat oil in a large pot and cook chicken until done",
      "Add vegetables and cook for 5 minutes",
      "Add broth and bring to a boil",
      "Add noodles and cook according to package directions",
      "Season with salt and pepper to taste",
    ],
    category: "Soup",
    createdAt: "2024-01-15",
  },
  {
    id: "16",
    title: "Meatball Subs",
    description: "Hearty meatball submarine sandwich with marinara sauce",
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&h=300&fit=crop",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "Easy",
    ingredients: ["12 meatballs", "4 sub rolls", "2 cups marinara sauce", "1 cup mozzarella cheese", "fresh basil"],
    instructions: [
      "Heat meatballs in marinara sauce until warmed through",
      "Split sub rolls and toast lightly",
      "Fill rolls with meatballs and sauce",
      "Top with mozzarella cheese",
      "Broil until cheese melts",
      "Garnish with fresh basil",
    ],
    category: "Lunch",
    createdAt: "2024-01-16",
  },
  {
    id: "17",
    title: "Fish Tacos",
    description: "Fresh and zesty fish tacos with crispy fish and tangy slaw",
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&h=300&fit=crop",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: "Easy",
    ingredients: ["1 lb white fish", "8 corn tortillas", "2 cups cabbage slaw", "1 lime", "cilantro", "chipotle sauce"],
    instructions: [
      "Season fish with cumin, chili powder, and salt",
      "Cook fish in a hot skillet until flaky",
      "Warm tortillas in a dry pan",
      "Fill tortillas with fish and cabbage slaw",
      "Top with cilantro and lime juice",
      "Drizzle with chipotle sauce",
    ],
    category: "Mexican",
    createdAt: "2024-01-17",
  },
  {
    id: "18",
    title: "Veggie Wrap",
    description: "Healthy vegetable wrap with hummus and fresh vegetables",
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&h=300&fit=crop",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "Easy",
    ingredients: ["2 large tortillas", "1/2 cup hummus", "1 cucumber", "1 tomato", "lettuce", "shredded carrots"],
    instructions: [
      "Spread hummus evenly on tortillas",
      "Layer with lettuce, cucumber, tomato, and carrots",
      "Season with salt and pepper",
      "Roll tightly, tucking in sides",
      "Cut in half diagonally",
      "Serve immediately or wrap for later",
    ],
    category: "Vegetarian",
    createdAt: "2024-01-18",
  },
  {
    id: "19",
    title: "Chocolate Chip Cookies",
    description: "Classic chewy chocolate chip cookies that everyone loves",
    image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&h=300&fit=crop",
    prepTime: 15,
    cookTime: 12,
    servings: 24,
    difficulty: "Easy",
    ingredients: [
      "2 cups flour",
      "1 cup butter",
      "3/4 cup brown sugar",
      "2 eggs",
      "2 cups chocolate chips",
      "1 tsp vanilla",
    ],
    instructions: [
      "Preheat oven to 375°F",
      "Cream butter and sugars until fluffy",
      "Beat in eggs and vanilla",
      "Mix in flour gradually",
      "Fold in chocolate chips",
      "Bake for 9-11 minutes until golden",
    ],
    category: "Dessert",
    createdAt: "2024-01-19",
  },
  {
    id: "20",
    title: "Greek Salad",
    description: "Fresh Mediterranean Greek salad with feta and olives",
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    ingredients: ["2 cucumbers", "3 tomatoes", "1/2 red onion", "1 cup feta cheese", "1/2 cup olives", "olive oil"],
    instructions: [
      "Chop cucumbers, tomatoes, and onion",
      "Combine vegetables in a large bowl",
      "Add feta cheese and olives",
      "Drizzle with olive oil and lemon juice",
      "Season with oregano, salt, and pepper",
      "Toss gently and serve",
    ],
    category: "Salad",
    createdAt: "2024-01-20",
  },

  // Medium Recipes (35 recipes)
  {
    id: "36",
    title: "Spaghetti Carbonara",
    description: "Classic Roman pasta dish with eggs, cheese, and pancetta",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400&h=300&fit=crop",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "400g spaghetti",
      "200g pancetta",
      "4 eggs",
      "100g Pecorino Romano",
      "2 cloves garlic",
      "Black pepper",
    ],
    instructions: [
      "Cook spaghetti in salted boiling water until al dente",
      "Cut pancetta into small cubes and cook until crispy",
      "Whisk eggs with grated cheese and black pepper",
      "Reserve pasta water and drain spaghetti",
      "Toss hot pasta with pancetta off the heat",
      "Add egg mixture and pasta water, tossing quickly to create a creamy sauce",
    ],
    category: "Italian",
    createdAt: "2024-01-21",
  },
  {
    id: "37",
    title: "Chicken Stir Fry",
    description: "Quick and healthy stir fry with fresh vegetables",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "1 lb chicken breast",
      "2 cups mixed vegetables",
      "3 tbsp soy sauce",
      "2 cloves garlic",
      "1 tbsp ginger",
      "2 tbsp oil",
    ],
    instructions: [
      "Cut chicken into bite-sized pieces",
      "Heat oil in a wok or large skillet over high heat",
      "Cook chicken until golden brown, about 5 minutes",
      "Add garlic and ginger, stir for 30 seconds",
      "Add vegetables and stir-fry for 3-4 minutes",
      "Add soy sauce and toss everything together",
    ],
    category: "Asian",
    createdAt: "2024-01-22",
  },
  {
    id: "38",
    title: "Beef Tacos",
    description: "Seasoned beef tacos with fresh toppings",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "1 lb ground beef",
      "8 taco shells",
      "1 onion",
      "2 cloves garlic",
      "1 tsp cumin",
      "1 cup shredded cheese",
    ],
    instructions: [
      "Cook ground beef in a large skillet until browned",
      "Add diced onion and garlic, cook until softened",
      "Season with cumin, salt, and pepper",
      "Warm taco shells according to package directions",
      "Fill shells with beef mixture",
      "Top with cheese and desired toppings",
    ],
    category: "Mexican",
    createdAt: "2024-01-23",
  },
  {
    id: "39",
    title: "Chicken Parmesan",
    description: "Breaded chicken with marinara sauce and melted cheese",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "4 chicken breasts",
      "1 cup breadcrumbs",
      "1 cup marinara sauce",
      "1 cup mozzarella",
      "1/2 cup parmesan",
      "2 eggs",
    ],
    instructions: [
      "Pound chicken breasts to even thickness",
      "Set up breading station with flour, beaten eggs, and breadcrumbs",
      "Bread chicken pieces and pan-fry until golden",
      "Top with marinara sauce and cheeses",
      "Bake at 375°F for 15 minutes until cheese melts",
      "Serve with pasta or salad",
    ],
    category: "Italian",
    createdAt: "2024-01-24",
  },
  {
    id: "40",
    title: "Pad Thai",
    description: "Sweet and tangy Thai noodles with shrimp",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "8 oz rice noodles",
      "1/2 lb shrimp",
      "2 eggs",
      "1 cup bean sprouts",
      "1/4 cup peanuts",
      "3 tbsp tamarind paste",
    ],
    instructions: [
      "Soak rice noodles in warm water until soft",
      "Heat oil in a wok and scramble eggs",
      "Add shrimp and cook until pink",
      "Add drained noodles and tamarind paste",
      "Toss in bean sprouts and cook for 2 minutes",
      "Garnish with peanuts and lime wedges",
    ],
    category: "Thai",
    createdAt: "2024-01-25",
  },
  {
    id: "41",
    title: "Chicken Tikka Masala",
    description: "Creamy Indian curry with tender chicken in spiced tomato sauce",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 30,
    cookTime: 40,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "2 lbs chicken",
      "1 cup yogurt",
      "2 cups tomato sauce",
      "1 cup heavy cream",
      "garam masala",
      "ginger",
    ],
    instructions: [
      "Marinate chicken in yogurt and spices for 2 hours",
      "Grill chicken until charred and cooked through",
      "Sauté onions, garlic, and ginger in oil",
      "Add tomato sauce and spices, simmer 10 minutes",
      "Stir in cream and grilled chicken",
      "Serve with basmati rice and naan",
    ],
    category: "Indian",
    createdAt: "2024-01-26",
  },
  {
    id: "42",
    title: "Fish and Chips",
    description: "Crispy beer-battered fish with golden french fries",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 25,
    cookTime: 30,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "2 lbs white fish",
      "2 lbs potatoes",
      "2 cups flour",
      "1 bottle beer",
      "oil for frying",
      "malt vinegar",
    ],
    instructions: [
      "Cut potatoes into thick chips and soak in water",
      "Make batter with flour, beer, and seasonings",
      "Heat oil to 350°F for frying",
      "Fry chips until golden, then drain",
      "Dip fish in batter and fry until crispy",
      "Serve with malt vinegar and mushy peas",
    ],
    category: "British",
    createdAt: "2024-01-27",
  },
  {
    id: "43",
    title: "Chicken Fajitas",
    description: "Sizzling chicken fajitas with peppers and onions",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    ingredients: ["2 lbs chicken breast", "3 bell peppers", "2 onions", "flour tortillas", "lime", "fajita seasoning"],
    instructions: [
      "Slice chicken, peppers, and onions into strips",
      "Season chicken with fajita spices",
      "Cook chicken in hot skillet until done",
      "Sauté peppers and onions until tender",
      "Warm tortillas and serve with toppings",
      "Garnish with lime wedges and cilantro",
    ],
    category: "Mexican",
    createdAt: "2024-01-28",
  },
  {
    id: "44",
    title: "Beef Stroganoff",
    description: "Creamy Russian beef dish with mushrooms and sour cream",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 20,
    cookTime: 35,
    servings: 6,
    difficulty: "Medium",
    ingredients: ["2 lbs beef sirloin", "1 lb mushrooms", "1 onion", "1 cup sour cream", "egg noodles", "beef broth"],
    instructions: [
      "Cut beef into thin strips and season",
      "Brown beef in batches, then set aside",
      "Sauté mushrooms and onions until soft",
      "Add beef broth and simmer",
      "Return beef to pan with sour cream",
      "Serve over cooked egg noodles",
    ],
    category: "Russian",
    createdAt: "2024-01-29",
  },
  {
    id: "45",
    title: "Chicken Curry",
    description: "Aromatic chicken curry with coconut milk and spices",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 25,
    cookTime: 30,
    servings: 6,
    difficulty: "Medium",
    ingredients: ["2 lbs chicken thighs", "1 can coconut milk", "curry powder", "onion", "garlic", "ginger"],
    instructions: [
      "Cut chicken into bite-sized pieces",
      "Sauté onions, garlic, and ginger",
      "Add curry powder and cook until fragrant",
      "Add chicken and brown on all sides",
      "Pour in coconut milk and simmer 20 minutes",
      "Serve with jasmine rice",
    ],
    category: "Indian",
    createdAt: "2024-01-30",
  },

  // Hard Recipes (35 recipes)
  {
    id: "71",
    title: "Beef Wellington",
    description: "Beef tenderloin wrapped in pastry with mushroom duxelles",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 45,
    cookTime: 60,
    servings: 6,
    difficulty: "Hard",
    ingredients: [
      "2 lb beef tenderloin",
      "1 lb puff pastry",
      "1 lb mushrooms",
      "4 oz pâté",
      "2 egg yolks",
      "Fresh herbs",
    ],
    instructions: [
      "Sear beef tenderloin on all sides until browned",
      "Prepare mushroom duxelles by finely chopping and cooking mushrooms",
      "Roll out puff pastry and spread with pâté",
      "Layer mushroom duxelles over pâté",
      "Wrap beef in pastry, sealing edges with egg wash",
      "Bake at 400°F for 25-30 minutes until pastry is golden",
    ],
    category: "British",
    createdAt: "2024-01-31",
  },
  {
    id: "72",
    title: "Chocolate Soufflé",
    description: "Light and airy chocolate dessert that rises beautifully",
    image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&h=300&fit=crop",
    prepTime: 30,
    cookTime: 45,
    servings: 6,
    difficulty: "Hard",
    ingredients: [
      "6 oz dark chocolate",
      "6 eggs",
      "4 tbsp butter",
      "1/4 cup sugar",
      "1/2 cup heavy cream",
      "1 tsp vanilla",
    ],
    instructions: [
      "Preheat oven to 375°F and prepare ramekins",
      "Melt chocolate with butter in a double boiler",
      "Separate eggs and whip whites to soft peaks",
      "Mix egg yolks with chocolate mixture",
      "Fold in whipped whites in three additions",
      "Bake for 12-15 minutes until risen and slightly wobbly",
    ],
    category: "French",
    createdAt: "2024-02-01",
  },
  {
    id: "73",
    title: "Duck Confit",
    description: "Slow-cooked duck legs in their own fat",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 60,
    cookTime: 240,
    servings: 4,
    difficulty: "Hard",
    ingredients: ["4 duck legs", "2 cups duck fat", "4 cloves garlic", "4 sprigs thyme", "2 tbsp salt", "2 bay leaves"],
    instructions: [
      "Cure duck legs with salt and herbs for 24 hours",
      "Rinse and pat dry the duck legs",
      "Slowly cook in duck fat at 200°F for 3-4 hours",
      "Duck should be tender and falling off the bone",
      "Store in fat until ready to serve",
      "Crisp skin under broiler before serving",
    ],
    category: "French",
    createdAt: "2024-02-02",
  },
  {
    id: "74",
    title: "Lobster Thermidor",
    description: "Luxurious lobster in cream sauce with cheese",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 30,
    cookTime: 45,
    servings: 4,
    difficulty: "Hard",
    ingredients: [
      "2 whole lobsters",
      "1/2 cup heavy cream",
      "2 egg yolks",
      "2 tbsp cognac",
      "1 tsp mustard",
      "1/2 cup gruyere cheese",
    ],
    instructions: [
      "Cook lobsters in boiling water for 8 minutes",
      "Remove meat from shells, reserve shells",
      "Make sauce with cream, egg yolks, and cognac",
      "Mix lobster meat with sauce",
      "Fill shells with mixture and top with cheese",
      "Broil until golden and bubbling",
    ],
    category: "French",
    createdAt: "2024-02-03",
  },
  {
    id: "75",
    title: "Coq au Vin",
    description: "Chicken braised in red wine with vegetables",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 30,
    cookTime: 90,
    servings: 6,
    difficulty: "Hard",
    ingredients: [
      "1 whole chicken",
      "1 bottle red wine",
      "4 oz bacon",
      "12 pearl onions",
      "8 oz mushrooms",
      "Fresh herbs",
    ],
    instructions: [
      "Cut chicken into pieces and season with salt and pepper",
      "Cook bacon until crispy, remove and set aside",
      "Brown chicken pieces in bacon fat",
      "Add wine and bring to a simmer",
      "Add vegetables and herbs, cover and braise for 1 hour",
      "Serve with crusty bread and the reduced wine sauce",
    ],
    category: "French",
    createdAt: "2024-02-04",
  },
  {
    id: "76",
    title: "Osso Buco",
    description: "Braised veal shanks with vegetables and gremolata",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 30,
    cookTime: 150,
    servings: 6,
    difficulty: "Hard",
    ingredients: ["6 veal shanks", "white wine", "tomatoes", "carrots", "celery", "gremolata"],
    instructions: [
      "Dredge veal shanks in flour and brown",
      "Sauté vegetables until softened",
      "Add wine and tomatoes, bring to simmer",
      "Return veal to pot and braise 2.5 hours",
      "Make gremolata with lemon, garlic, parsley",
      "Serve with risotto and gremolata",
    ],
    category: "Italian",
    createdAt: "2024-02-05",
  },
  {
    id: "77",
    title: "Bouillabaisse",
    description: "Provençal fish stew with saffron and rouille",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 45,
    cookTime: 60,
    servings: 8,
    difficulty: "Hard",
    ingredients: ["mixed fish", "shellfish", "saffron", "fennel", "tomatoes", "rouille"],
    instructions: [
      "Prepare fish stock with bones and aromatics",
      "Sauté fennel, onions, and tomatoes",
      "Add saffron and white wine",
      "Add firm fish first, then delicate fish",
      "Serve with rouille and crusty bread",
      "Garnish with fresh herbs",
    ],
    category: "French",
    createdAt: "2024-02-06",
  },
  {
    id: "78",
    title: "Peking Duck",
    description: "Crispy skin duck with pancakes and hoisin sauce",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 60,
    cookTime: 180,
    servings: 6,
    difficulty: "Hard",
    ingredients: ["whole duck", "hoisin sauce", "pancakes", "cucumber", "scallions", "five spice"],
    instructions: [
      "Prepare duck with five spice rub",
      "Air dry duck for 24 hours",
      "Roast at high heat for crispy skin",
      "Carve duck tableside",
      "Serve with pancakes and condiments",
      "Garnish with cucumber and scallions",
    ],
    category: "Chinese",
    createdAt: "2024-02-07",
  },
  {
    id: "79",
    title: "Paella Valenciana",
    description: "Traditional Spanish rice dish with chicken and vegetables",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 30,
    cookTime: 45,
    servings: 8,
    difficulty: "Hard",
    ingredients: ["bomba rice", "chicken", "rabbit", "green beans", "saffron", "paprika"],
    instructions: [
      "Heat paella pan and add olive oil",
      "Brown chicken and rabbit pieces",
      "Add vegetables and sauté briefly",
      "Add rice and saffron stock",
      "Simmer without stirring for 20 minutes",
      "Rest for 5 minutes before serving",
    ],
    category: "Spanish",
    createdAt: "2024-02-08",
  },
  {
    id: "80",
    title: "Ratatouille",
    description: "Provençal vegetable stew with eggplant and zucchini",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    prepTime: 45,
    cookTime: 90,
    servings: 6,
    difficulty: "Hard",
    ingredients: ["eggplant", "zucchini", "tomatoes", "bell peppers", "onions", "herbs de Provence"],
    instructions: [
      "Slice vegetables into uniform rounds",
      "Make tomato base with onions and herbs",
      "Arrange vegetables in overlapping pattern",
      "Drizzle with herb oil",
      "Bake covered, then uncovered until tender",
      "Serve as side or main dish",
    ],
    category: "French",
    createdAt: "2024-02-09",
  },
]

// Generate more recipes to reach 105 total
const generateMoreRecipes = (): Recipe[] => {
  const additionalRecipes: Recipe[] = []

  // Add more Easy recipes (15 more to reach 35)
  const easyRecipeData = [
    { name: "BLT Sandwich", emoji: "🥓", bg: "ff6347", category: "Sandwich" },
    { name: "Fruit Salad", emoji: "🍇", bg: "ff69b4", category: "Dessert" },
    { name: "Garlic Bread", emoji: "🧄", bg: "daa520", category: "Side" },
    { name: "Chicken Wings", emoji: "🍗", bg: "ff6347", category: "Appetizer" },
    { name: "Mashed Potatoes", emoji: "🥔", bg: "f5deb3", category: "Side" },
    { name: "Corn Salad", emoji: "🌽", bg: "ffd700", category: "Salad" },
    { name: "Deviled Eggs", emoji: "🥚", bg: "fff8dc", category: "Appetizer" },
    { name: "Chicken Quesadilla", emoji: "🐔", bg: "ff6347", category: "Mexican" },
    { name: "Tomato Soup", emoji: "🍅", bg: "ff6347", category: "Soup" },
    { name: "Club Sandwich", emoji: "🥪", bg: "8b4513", category: "Sandwich" },
    { name: "Baked Potato", emoji: "🥔", bg: "8b4513", category: "Side" },
    { name: "Chicken Salad Wrap", emoji: "🌯", bg: "90ee90", category: "Lunch" },
    { name: "Veggie Burger", emoji: "🍔", bg: "90ee90", category: "Vegetarian" },
    { name: "Chicken Noodle Soup", emoji: "🍜", bg: "ffd700", category: "Soup" },
    { name: "Stuffed Peppers", emoji: "🫑", bg: "ff6347", category: "Dinner" },
  ]

  easyRecipeData.forEach((recipe, index) => {
    additionalRecipes.push({
      id: `${21 + index}`,
      title: recipe.name,
      description: `Delicious ${recipe.name.toLowerCase()} recipe`,
      image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=400&h=300&fit=crop",
      prepTime: Math.floor(Math.random() * 20) + 5,
      cookTime: Math.floor(Math.random() * 30) + 10,
      servings: Math.floor(Math.random() * 6) + 2,
      difficulty: "Easy",
      ingredients: ["ingredient 1", "ingredient 2", "ingredient 3", "ingredient 4"],
      instructions: ["Step 1", "Step 2", "Step 3", "Step 4"],
      category: recipe.category,
      createdAt: `2024-01-${21 + index}`,
    })
  })

  // Add more Medium recipes (25 more to reach 35)
  const mediumRecipeData = [
    { name: "Lasagna", emoji: "🍝", bg: "ff6347", category: "Italian" },
    { name: "Chicken Teriyaki", emoji: "🍗", bg: "8b4513", category: "Japanese" },
    { name: "Shepherd's Pie", emoji: "🥧", bg: "8b4513", category: "British" },
    { name: "Chicken Enchiladas", emoji: "🌯", bg: "ff6347", category: "Mexican" },
    { name: "Pork Chops", emoji: "🥩", bg: "8b4513", category: "American" },
    { name: "Chicken Marsala", emoji: "🍗", bg: "722f37", category: "Italian" },
    { name: "Beef Chili", emoji: "🌶️", bg: "ff4500", category: "American" },
    { name: "Chicken Alfredo", emoji: "🍝", bg: "fff8dc", category: "Italian" },
    { name: "Salmon Teriyaki", emoji: "🐟", bg: "ff8c00", category: "Japanese" },
    { name: "Chicken Cacciatore", emoji: "🍗", bg: "ff6347", category: "Italian" },
    { name: "Beef Bourguignon", emoji: "🥩", bg: "722f37", category: "French" },
    { name: "Chicken Piccata", emoji: "🍗", bg: "fff8dc", category: "Italian" },
    { name: "Pork Tenderloin", emoji: "🥩", bg: "8b4513", category: "American" },
    { name: "Chicken Cordon Bleu", emoji: "🍗", bg: "fff8dc", category: "French" },
    { name: "Beef Stir Fry", emoji: "🥩", bg: "8b4513", category: "Asian" },
    { name: "Chicken Pot Pie", emoji: "🥧", bg: "daa520", category: "American" },
    { name: "Shrimp Scampi", emoji: "🦐", bg: "fff8dc", category: "Italian" },
    { name: "Chicken Shawarma", emoji: "🥙", bg: "daa520", category: "Middle Eastern" },
    { name: "Beef Tacos al Pastor", emoji: "🌮", bg: "ff6347", category: "Mexican" },
    { name: "Chicken Satay", emoji: "🍗", bg: "ff8c00", category: "Thai" },
    { name: "Pork Carnitas", emoji: "🥩", bg: "8b4513", category: "Mexican" },
    { name: "Chicken Biryani", emoji: "🍛", bg: "ff8c00", category: "Indian" },
    { name: "Fish Curry", emoji: "🐟", bg: "ff8c00", category: "Indian" },
    { name: "Chicken Adobo", emoji: "🍗", bg: "8b4513", category: "Filipino" },
    { name: "Beef Bulgogi", emoji: "🥩", bg: "8b4513", category: "Korean" },
  ]

  mediumRecipeData.forEach((recipe, index) => {
    additionalRecipes.push({
      id: `${46 + index}`,
      title: recipe.name,
      description: `Flavorful ${recipe.name.toLowerCase()} with authentic spices`,
      image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
      prepTime: Math.floor(Math.random() * 30) + 15,
      cookTime: Math.floor(Math.random() * 60) + 20,
      servings: Math.floor(Math.random() * 6) + 4,
      difficulty: "Medium",
      ingredients: ["ingredient 1", "ingredient 2", "ingredient 3", "ingredient 4", "ingredient 5"],
      instructions: ["Step 1", "Step 2", "Step 3", "Step 4", "Step 5"],
      category: recipe.category,
      createdAt: `2024-02-${10 + index}`,
    })
  })

  // Add more Hard recipes (25 more to reach 35)
  const hardRecipeData = [
    { name: "Lamb Tagine", emoji: "🐑", bg: "8b4513", category: "Moroccan" },
    { name: "Cioppino", emoji: "🦀", bg: "ff4500", category: "Italian-American" },
    { name: "Cassoulet", emoji: "🫘", bg: "8b4513", category: "French" },
    { name: "Chicken Kiev", emoji: "🍗", bg: "fff8dc", category: "Ukrainian" },
    { name: "Risotto Milanese", emoji: "🍚", bg: "fff8dc", category: "Italian" },
    { name: "Chicken Mole", emoji: "🍗", bg: "8b4513", category: "Mexican" },
    { name: "Seafood Paella", emoji: "🥘", bg: "ff8c00", category: "Spanish" },
    { name: "Rack of Lamb", emoji: "🐑", bg: "8b4513", category: "French" },
    { name: "Lobster Bisque", emoji: "🦞", bg: "ff4500", category: "French" },
    { name: "Chicken Ballotine", emoji: "🍗", bg: "8b4513", category: "French" },
    { name: "Fish en Papillote", emoji: "🐟", bg: "87ceeb", category: "French" },
    { name: "Beef Tenderloin", emoji: "🥩", bg: "8b4513", category: "French" },
    { name: "Chicken Galantine", emoji: "🍗", bg: "8b4513", category: "French" },
    { name: "Veal Oscar", emoji: "🥩", bg: "fff8dc", category: "French" },
    { name: "Duck à l'Orange", emoji: "🦆", bg: "ff8c00", category: "French" },
    { name: "Beef Roulade", emoji: "🥩", bg: "8b4513", category: "German" },
    { name: "Salmon Wellington", emoji: "🐟", bg: "ff8c00", category: "British" },
    { name: "Chicken Roulade", emoji: "🍗", bg: "8b4513", category: "French" },
    { name: "Beef Carpaccio", emoji: "🥩", bg: "ff4500", category: "Italian" },
    { name: "Lobster Newburg", emoji: "🦞", bg: "ff4500", category: "American" },
    { name: "Chicken Chasseur", emoji: "🍗", bg: "8b4513", category: "French" },
    { name: "Veal Saltimbocca", emoji: "🥩", bg: "fff8dc", category: "Italian" },
    { name: "Tournedos Rossini", emoji: "🥩", bg: "8b4513", category: "French" },
    { name: "Sole Meunière", emoji: "🐟", bg: "fff8dc", category: "French" },
    { name: "Beef Short Ribs", emoji: "🥩", bg: "8b4513", category: "American" },
  ]

  hardRecipeData.forEach((recipe, index) => {
    additionalRecipes.push({
      id: `${81 + index}`,
      title: recipe.name,
      description: `Sophisticated ${recipe.name.toLowerCase()} for special occasions`,
      image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
      prepTime: Math.floor(Math.random() * 60) + 30,
      cookTime: Math.floor(Math.random() * 180) + 45,
      servings: Math.floor(Math.random() * 8) + 4,
      difficulty: "Hard",
      ingredients: ["ingredient 1", "ingredient 2", "ingredient 3", "ingredient 4", "ingredient 5", "ingredient 6"],
      instructions: ["Step 1", "Step 2", "Step 3", "Step 4", "Step 5", "Step 6"],
      category: recipe.category,
      createdAt: `2024-03-${1 + index}`,
    })
  })

  return additionalRecipes
}

export const allCompleteRecipes = [...completeRecipes, ...generateMoreRecipes()]
