import type { Recipe, User } from "./types"

// Sample recipes data
export const initialRecipes: Recipe[] = [
  {
    id: "1",
    title: "Scrambled Eggs",
    description: "Fluffy and creamy scrambled eggs perfect for breakfast",
    image: "/placeholder.svg?height=300&width=400&text=🍳+Scrambled+Eggs&bg=fff8dc",
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    difficulty: "Easy",
    ingredients: ["4 eggs", "2 tbsp butter", "1/4 tsp salt", "1/8 tsp pepper", "2 tbsp milk"],
    instructions: [
      "Crack eggs into a bowl and whisk with milk, salt, and pepper",
      "Heat butter in a non-stick pan over medium-low heat",
      "Pour in eggs and let sit for 20 seconds",
      "Gently stir with a spatula, pushing eggs from edges to center",
      "Continue stirring gently until eggs are just set but still creamy",
      "Remove from heat and serve immediately",
    ],
    category: "Breakfast",
    createdAt: "2024-01-01",
    story:
      "My grandmother taught me this technique when I was eight years old. She always said the secret was low heat and patience - 'Good eggs can't be rushed, dear.' Every Sunday morning, she'd make these for the whole family, and the kitchen would fill with the most wonderful aroma.",
  },
  {
    id: "2",
    title: "Pancakes",
    description: "Classic fluffy pancakes that are perfect for weekend mornings",
    image: "/placeholder.svg?height=300&width=400&text=🥞+Fluffy+Pancakes&bg=fff8dc",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "2 cups all-purpose flour",
      "2 eggs",
      "1 3/4 cups milk",
      "1/4 cup melted butter",
      "2 tbsp sugar",
      "2 tsp baking powder",
    ],
    instructions: [
      "Mix flour, sugar, and baking powder in a large bowl",
      "In another bowl, whisk eggs, milk, and melted butter",
      "Pour wet ingredients into dry ingredients and stir until just combined",
      "Heat a griddle or large pan over medium heat",
      "Pour 1/4 cup batter for each pancake",
      "Cook until bubbles form on surface, then flip and cook until golden",
    ],
    category: "Breakfast",
    createdAt: "2024-01-02",
  },
  {
    id: "3",
    title: "Grilled Cheese",
    description: "Golden crispy grilled cheese sandwich with melted cheese inside",
    image: "/placeholder.svg?height=300&width=400&text=🧀+Grilled+Cheese&bg=ffd700",
    prepTime: 5,
    cookTime: 8,
    servings: 1,
    difficulty: "Easy",
    ingredients: ["2 slices bread", "2 slices cheese", "2 tbsp butter"],
    instructions: [
      "Butter one side of each bread slice",
      "Place cheese between bread slices, buttered sides out",
      "Heat a pan over medium heat",
      "Cook sandwich for 3-4 minutes until golden brown",
      "Flip and cook another 3-4 minutes until other side is golden",
      "Cut diagonally and serve hot",
    ],
    category: "Lunch",
    createdAt: "2024-01-03",
  },
  {
    id: "4",
    title: "Caesar Salad",
    description: "Classic Caesar salad with crisp romaine and homemade dressing",
    image: "/placeholder.svg?height=300&width=400&text=🥗+Caesar+Salad&bg=90ee90",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "1 head romaine lettuce",
      "1/2 cup croutons",
      "1/4 cup parmesan cheese",
      "2 anchovy fillets",
      "1/4 cup Caesar dressing",
    ],
    instructions: [
      "Wash and chop romaine lettuce into bite-sized pieces",
      "Place lettuce in a large salad bowl",
      "Add croutons and toss gently",
      "Drizzle with Caesar dressing",
      "Top with grated parmesan and anchovy fillets",
      "Toss everything together and serve immediately",
    ],
    category: "Salad",
    createdAt: "2024-01-04",
  },
  {
    id: "36",
    title: "Spaghetti Carbonara",
    description: "Classic Roman pasta dish with eggs, cheese, and pancetta",
    image: "/placeholder.svg?height=300&width=400&text=🍝+Carbonara&bg=fff8dc",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "400g spaghetti",
      "200g pancetta",
      "4 eggs",
      "100g Pecorino Romano",
      "2 cloves garlic",
      "Black pepper",
    ],
    instructions: [
      "Cook spaghetti in salted boiling water until al dente",
      "Cut pancetta into small cubes and cook until crispy",
      "Whisk eggs with grated cheese and black pepper",
      "Reserve pasta water and drain spaghetti",
      "Toss hot pasta with pancetta off the heat",
      "Add egg mixture and pasta water, tossing quickly to create a creamy sauce",
    ],
    category: "Italian",
    createdAt: "2024-01-16",
    story:
      "This recipe reminds me of my first trip to Rome when I was 22. I was wandering through the cobblestone streets near the Pantheon when I stumbled upon a tiny trattoria tucked away in an alley. The elderly owner, Giuseppe, noticed I was American and insisted on teaching me the 'real' way to make carbonara.",
  },
  {
    id: "37",
    title: "Chicken Stir Fry",
    description: "Quick and healthy stir fry with fresh vegetables",
    image: "/placeholder.svg?height=300&width=400&text=🥘+Stir+Fry&bg=ff6347",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "1 lb chicken breast",
      "2 cups mixed vegetables",
      "3 tbsp soy sauce",
      "2 cloves garlic",
      "1 tbsp ginger",
      "2 tbsp oil",
    ],
    instructions: [
      "Cut chicken into bite-sized pieces",
      "Heat oil in a wok or large skillet over high heat",
      "Cook chicken until golden brown, about 5 minutes",
      "Add garlic and ginger, stir for 30 seconds",
      "Add vegetables and stir-fry for 3-4 minutes",
      "Add soy sauce and toss everything together",
    ],
    category: "Asian",
    createdAt: "2024-01-17",
  },
  {
    id: "71",
    title: "Beef Wellington",
    description: "Beef tenderloin wrapped in pastry with mushroom duxelles",
    image: "/placeholder.svg?height=300&width=400&text=🥩+Beef+Wellington&bg=8b4513",
    prepTime: 45,
    cookTime: 60,
    servings: 6,
    difficulty: "Hard",
    ingredients: [
      "2 lb beef tenderloin",
      "1 lb puff pastry",
      "1 lb mushrooms",
      "4 oz pâté",
      "2 egg yolks",
      "Fresh herbs",
    ],
    instructions: [
      "Sear beef tenderloin on all sides until browned",
      "Prepare mushroom duxelles by finely chopping and cooking mushrooms",
      "Roll out puff pastry and spread with pâté",
      "Layer mushroom duxelles over pâté",
      "Wrap beef in pastry, sealing edges with egg wash",
      "Bake at 400°F for 25-30 minutes until pastry is golden",
    ],
    category: "British",
    createdAt: "2024-01-21",
  },
  {
    id: "72",
    title: "Chocolate Soufflé",
    description: "Light and airy chocolate dessert that rises beautifully",
    image: "/placeholder.svg?height=300&width=400&text=🍫+Soufflé&bg=2f1b14",
    prepTime: 30,
    cookTime: 45,
    servings: 6,
    difficulty: "Hard",
    ingredients: [
      "6 oz dark chocolate",
      "6 eggs",
      "4 tbsp butter",
      "1/4 cup sugar",
      "1/2 cup heavy cream",
      "1 tsp vanilla",
    ],
    instructions: [
      "Preheat oven to 375°F and prepare ramekins",
      "Melt chocolate with butter in a double boiler",
      "Separate eggs and whip whites to soft peaks",
      "Mix egg yolks with chocolate mixture",
      "Fold in whipped whites in three additions",
      "Bake for 12-15 minutes until risen and slightly wobbly",
    ],
    category: "French",
    createdAt: "2024-01-22",
  },
]

// Sample admin user
export const adminUser: User = {
  id: "1",
  email: "admin@cooking.com",
  password: "admin123", // In production, this should be hashed
  role: "admin",
}
