export interface GameRecipe {
  name: string
  ingredients: string[]
  difficulty: "Easy" | "Medium" | "Hard"
  cookTime: number
  category: string
  description: string
}

export const gameRecipes: GameRecipe[] = [
  // Easy Recipes (35 recipes)
  {
    name: "Scrambled Eggs",
    ingredients: ["eggs", "butter", "salt", "pepper", "milk"],
    difficulty: "Easy",
    cookTime: 5,
    category: "Breakfast",
    description: "Fluffy and creamy scrambled eggs",
  },
  {
    name: "Pancakes",
    ingredients: ["flour", "eggs", "milk", "butter", "sugar", "baking powder"],
    difficulty: "Easy",
    cookTime: 15,
    category: "Breakfast",
    description: "Classic fluffy pancakes",
  },
  {
    name: "Grilled Cheese",
    ingredients: ["bread", "cheese", "butter"],
    difficulty: "Easy",
    cookTime: 8,
    category: "Lunch",
    description: "Golden crispy grilled cheese sandwich",
  },
  {
    name: "Caesar Salad",
    ingredients: ["lettuce", "croutons", "parmesan", "anchovies", "dressing"],
    difficulty: "Easy",
    cookTime: 10,
    category: "Salad",
    description: "Classic Caesar salad with crisp romaine",
  },
  {
    name: "Pasta with Butter",
    ingredients: ["pasta", "butter", "parmesan", "salt", "pepper"],
    difficulty: "Easy",
    cookTime: 12,
    category: "Italian",
    description: "Simple buttered pasta with cheese",
  },
  {
    name: "French Toast",
    ingredients: ["bread", "eggs", "milk", "cinnamon", "vanilla", "butter"],
    difficulty: "Easy",
    cookTime: 10,
    category: "Breakfast",
    description: "Sweet and custardy French toast",
  },
  {
    name: "Quesadilla",
    ingredients: ["tortilla", "cheese", "chicken", "peppers", "onions"],
    difficulty: "Easy",
    cookTime: 8,
    category: "Mexican",
    description: "Crispy cheese-filled quesadilla",
  },
  {
    name: "Smoothie Bowl",
    ingredients: ["banana", "berries", "yogurt", "granola", "honey"],
    difficulty: "Easy",
    cookTime: 5,
    category: "Breakfast",
    description: "Healthy and colorful smoothie bowl",
  },
  {
    name: "Avocado Toast",
    ingredients: ["bread", "avocado", "lemon", "salt", "pepper", "tomato"],
    difficulty: "Easy",
    cookTime: 5,
    category: "Breakfast",
    description: "Trendy avocado toast with toppings",
  },
  {
    name: "Chicken Salad",
    ingredients: ["chicken", "mayo", "celery", "grapes", "nuts", "lettuce"],
    difficulty: "Easy",
    cookTime: 15,
    category: "Salad",
    description: "Creamy chicken salad with fruit and nuts",
  },
  {
    name: "Tuna Sandwich",
    ingredients: ["tuna", "mayo", "bread", "lettuce", "tomato", "onion"],
    difficulty: "Easy",
    cookTime: 5,
    category: "Lunch",
    description: "Classic tuna salad sandwich",
  },
  {
    name: "Oatmeal",
    ingredients: ["oats", "milk", "banana", "honey", "cinnamon"],
    difficulty: "Easy",
    cookTime: 8,
    category: "Breakfast",
    description: "Warm and comforting oatmeal",
  },
  {
    name: "Caprese Salad",
    ingredients: ["tomato", "mozzarella", "basil", "olive oil", "balsamic"],
    difficulty: "Easy",
    cookTime: 5,
    category: "Salad",
    description: "Fresh Italian caprese salad",
  },
  {
    name: "Banana Bread",
    ingredients: ["banana", "flour", "sugar", "eggs", "butter", "baking soda"],
    difficulty: "Easy",
    cookTime: 60,
    category: "Dessert",
    description: "Moist and sweet banana bread",
  },
  {
    name: "Chicken Soup",
    ingredients: ["chicken", "carrots", "celery", "onion", "noodles", "broth"],
    difficulty: "Easy",
    cookTime: 30,
    category: "Soup",
    description: "Comforting chicken noodle soup",
  },
  {
    name: "Meatball Subs",
    ingredients: ["meatballs", "marinara", "bread", "mozzarella", "basil"],
    difficulty: "Easy",
    cookTime: 20,
    category: "Sandwich",
    description: "Hearty meatball submarine sandwich",
  },
  {
    name: "Fish Tacos",
    ingredients: ["fish", "tortilla", "cabbage", "lime", "cilantro", "sauce"],
    difficulty: "Easy",
    cookTime: 15,
    category: "Mexican",
    description: "Fresh and zesty fish tacos",
  },
  {
    name: "Veggie Wrap",
    ingredients: ["tortilla", "hummus", "cucumber", "tomato", "lettuce", "carrots"],
    difficulty: "Easy",
    cookTime: 5,
    category: "Lunch",
    description: "Healthy vegetable wrap",
  },
  {
    name: "Chocolate Chip Cookies",
    ingredients: ["flour", "butter", "sugar", "eggs", "chocolate chips", "vanilla"],
    difficulty: "Easy",
    cookTime: 12,
    category: "Dessert",
    description: "Classic chewy chocolate chip cookies",
  },
  {
    name: "Greek Salad",
    ingredients: ["cucumber", "tomato", "olives", "feta", "onion", "olive oil"],
    difficulty: "Easy",
    cookTime: 10,
    category: "Salad",
    description: "Fresh Mediterranean Greek salad",
  },
  {
    name: "BLT Sandwich",
    ingredients: ["bacon", "lettuce", "tomato", "bread", "mayo"],
    difficulty: "Easy",
    cookTime: 10,
    category: "Sandwich",
    description: "Classic bacon, lettuce, and tomato sandwich",
  },
  {
    name: "Fruit Salad",
    ingredients: ["strawberries", "grapes", "apple", "orange", "honey", "mint"],
    difficulty: "Easy",
    cookTime: 10,
    category: "Dessert",
    description: "Fresh mixed fruit salad",
  },
  {
    name: "Garlic Bread",
    ingredients: ["bread", "garlic", "butter", "parsley", "parmesan"],
    difficulty: "Easy",
    cookTime: 10,
    category: "Side",
    description: "Crispy garlic bread with herbs",
  },
  {
    name: "Chicken Wings",
    ingredients: ["chicken wings", "hot sauce", "butter", "celery", "ranch"],
    difficulty: "Easy",
    cookTime: 25,
    category: "Appetizer",
    description: "Spicy buffalo chicken wings",
  },
  {
    name: "Mashed Potatoes",
    ingredients: ["potatoes", "butter", "milk", "salt", "pepper"],
    difficulty: "Easy",
    cookTime: 20,
    category: "Side",
    description: "Creamy mashed potatoes",
  },
  {
    name: "Corn Salad",
    ingredients: ["corn", "tomato", "onion", "cilantro", "lime", "olive oil"],
    difficulty: "Easy",
    cookTime: 10,
    category: "Salad",
    description: "Fresh corn and tomato salad",
  },
  {
    name: "Deviled Eggs",
    ingredients: ["eggs", "mayo", "mustard", "paprika", "salt"],
    difficulty: "Easy",
    cookTime: 15,
    category: "Appetizer",
    description: "Classic deviled eggs",
  },
  {
    name: "Chicken Quesadilla",
    ingredients: ["chicken", "tortilla", "cheese", "peppers", "onions", "salsa"],
    difficulty: "Easy",
    cookTime: 12,
    category: "Mexican",
    description: "Crispy chicken and cheese quesadilla",
  },
  {
    name: "Tomato Soup",
    ingredients: ["tomatoes", "onion", "garlic", "cream", "basil", "broth"],
    difficulty: "Easy",
    cookTime: 25,
    category: "Soup",
    description: "Creamy tomato soup",
  },
  {
    name: "Club Sandwich",
    ingredients: ["turkey", "bacon", "lettuce", "tomato", "bread", "mayo"],
    difficulty: "Easy",
    cookTime: 10,
    category: "Sandwich",
    description: "Triple-decker club sandwich",
  },
  {
    name: "Baked Potato",
    ingredients: ["potato", "butter", "sour cream", "chives", "cheese", "bacon"],
    difficulty: "Easy",
    cookTime: 45,
    category: "Side",
    description: "Loaded baked potato",
  },
  {
    name: "Chicken Salad Wrap",
    ingredients: ["chicken", "mayo", "grapes", "celery", "tortilla", "lettuce"],
    difficulty: "Easy",
    cookTime: 10,
    category: "Lunch",
    description: "Chicken salad in a wrap",
  },
  {
    name: "Veggie Burger",
    ingredients: ["black beans", "quinoa", "onion", "garlic", "breadcrumbs", "spices"],
    difficulty: "Easy",
    cookTime: 20,
    category: "Vegetarian",
    description: "Homemade veggie burger",
  },
  {
    name: "Chicken Noodle Soup",
    ingredients: ["chicken", "noodles", "carrots", "celery", "onion", "broth"],
    difficulty: "Easy",
    cookTime: 30,
    category: "Soup",
    description: "Classic chicken noodle soup",
  },
  {
    name: "Stuffed Peppers",
    ingredients: ["bell peppers", "ground beef", "rice", "onion", "cheese", "tomato sauce"],
    difficulty: "Easy",
    cookTime: 35,
    category: "Dinner",
    description: "Bell peppers stuffed with beef and rice",
  },

  // Medium Recipes (35 recipes)
  {
    name: "Spaghetti Carbonara",
    ingredients: ["spaghetti", "eggs", "bacon", "parmesan", "pepper", "garlic"],
    difficulty: "Medium",
    cookTime: 25,
    category: "Italian",
    description: "Classic Roman pasta dish",
  },
  {
    name: "Chicken Stir Fry",
    ingredients: ["chicken", "vegetables", "soy sauce", "garlic", "ginger", "oil"],
    difficulty: "Medium",
    cookTime: 20,
    category: "Asian",
    description: "Quick and healthy stir fry",
  },
  {
    name: "Beef Tacos",
    ingredients: ["ground beef", "tortillas", "onion", "garlic", "cumin", "cheese"],
    difficulty: "Medium",
    cookTime: 20,
    category: "Mexican",
    description: "Seasoned beef tacos",
  },
  {
    name: "Chicken Parmesan",
    ingredients: ["chicken", "breadcrumbs", "marinara", "mozzarella", "parmesan", "eggs"],
    difficulty: "Medium",
    cookTime: 30,
    category: "Italian",
    description: "Breaded chicken with cheese and sauce",
  },
  {
    name: "Pad Thai",
    ingredients: ["rice noodles", "shrimp", "eggs", "bean sprouts", "peanuts", "tamarind"],
    difficulty: "Medium",
    cookTime: 25,
    category: "Thai",
    description: "Sweet and tangy Thai noodles",
  },
  {
    name: "Chicken Tikka Masala",
    ingredients: ["chicken", "yogurt", "tomatoes", "cream", "spices", "onion"],
    difficulty: "Medium",
    cookTime: 40,
    category: "Indian",
    description: "Creamy Indian curry",
  },
  {
    name: "Fish and Chips",
    ingredients: ["fish", "potatoes", "flour", "beer", "oil", "vinegar"],
    difficulty: "Medium",
    cookTime: 30,
    category: "British",
    description: "Crispy battered fish with fries",
  },
  {
    name: "Chicken Fajitas",
    ingredients: ["chicken", "peppers", "onions", "tortillas", "lime", "spices"],
    difficulty: "Medium",
    cookTime: 25,
    category: "Mexican",
    description: "Sizzling chicken fajitas",
  },
  {
    name: "Beef Stroganoff",
    ingredients: ["beef", "mushrooms", "onion", "sour cream", "noodles", "broth"],
    difficulty: "Medium",
    cookTime: 35,
    category: "Russian",
    description: "Creamy beef and mushroom dish",
  },
  {
    name: "Chicken Curry",
    ingredients: ["chicken", "coconut milk", "curry powder", "onion", "garlic", "ginger"],
    difficulty: "Medium",
    cookTime: 30,
    category: "Indian",
    description: "Aromatic chicken curry",
  },
  {
    name: "Lasagna",
    ingredients: ["pasta sheets", "ground beef", "ricotta", "mozzarella", "marinara", "herbs"],
    difficulty: "Medium",
    cookTime: 60,
    category: "Italian",
    description: "Layered pasta with meat and cheese",
  },
  {
    name: "Chicken Teriyaki",
    ingredients: ["chicken", "soy sauce", "mirin", "sugar", "ginger", "garlic"],
    difficulty: "Medium",
    cookTime: 25,
    category: "Japanese",
    description: "Sweet and savory glazed chicken",
  },
  {
    name: "Shepherd's Pie",
    ingredients: ["ground lamb", "vegetables", "potatoes", "gravy", "herbs", "cheese"],
    difficulty: "Medium",
    cookTime: 45,
    category: "British",
    description: "Meat and vegetable pie topped with mashed potatoes",
  },
  {
    name: "Chicken Enchiladas",
    ingredients: ["chicken", "tortillas", "enchilada sauce", "cheese", "onion", "cilantro"],
    difficulty: "Medium",
    cookTime: 35,
    category: "Mexican",
    description: "Rolled tortillas with chicken and sauce",
  },
  {
    name: "Pork Chops",
    ingredients: ["pork chops", "apples", "onion", "sage", "butter", "wine"],
    difficulty: "Medium",
    cookTime: 25,
    category: "American",
    description: "Pan-seared pork chops with apple",
  },
  {
    name: "Chicken Marsala",
    ingredients: ["chicken", "mushrooms", "marsala wine", "cream", "flour", "herbs"],
    difficulty: "Medium",
    cookTime: 30,
    category: "Italian",
    description: "Chicken in wine and mushroom sauce",
  },
  {
    name: "Beef Chili",
    ingredients: ["ground beef", "beans", "tomatoes", "onion", "chili powder", "cumin"],
    difficulty: "Medium",
    cookTime: 45,
    category: "American",
    description: "Hearty beef and bean chili",
  },
  {
    name: "Chicken Alfredo",
    ingredients: ["chicken", "fettuccine", "cream", "parmesan", "garlic", "butter"],
    difficulty: "Medium",
    cookTime: 25,
    category: "Italian",
    description: "Creamy pasta with chicken",
  },
  {
    name: "Salmon Teriyaki",
    ingredients: ["salmon", "soy sauce", "mirin", "sugar", "ginger", "sesame"],
    difficulty: "Medium",
    cookTime: 20,
    category: "Japanese",
    description: "Glazed salmon with Asian flavors",
  },
  {
    name: "Chicken Cacciatore",
    ingredients: ["chicken", "tomatoes", "peppers", "onion", "wine", "herbs"],
    difficulty: "Medium",
    cookTime: 40,
    category: "Italian",
    description: "Hunter-style chicken stew",
  },
  {
    name: "Beef Bourguignon",
    ingredients: ["beef", "red wine", "mushrooms", "onions", "carrots", "herbs"],
    difficulty: "Medium",
    cookTime: 120,
    category: "French",
    description: "Classic French beef stew",
  },
  {
    name: "Chicken Piccata",
    ingredients: ["chicken", "lemon", "capers", "white wine", "butter", "flour"],
    difficulty: "Medium",
    cookTime: 25,
    category: "Italian",
    description: "Lemon and caper chicken",
  },
  {
    name: "Pork Tenderloin",
    ingredients: ["pork tenderloin", "herbs", "garlic", "mustard", "honey", "vegetables"],
    difficulty: "Medium",
    cookTime: 35,
    category: "American",
    description: "Herb-crusted pork tenderloin",
  },
  {
    name: "Chicken Cordon Bleu",
    ingredients: ["chicken", "ham", "swiss cheese", "breadcrumbs", "eggs", "flour"],
    difficulty: "Medium",
    cookTime: 30,
    category: "French",
    description: "Stuffed and breaded chicken",
  },
  {
    name: "Beef Stir Fry",
    ingredients: ["beef", "broccoli", "soy sauce", "garlic", "ginger", "cornstarch"],
    difficulty: "Medium",
    cookTime: 20,
    category: "Asian",
    description: "Quick beef and vegetable stir fry",
  },
  {
    name: "Chicken Pot Pie",
    ingredients: ["chicken", "vegetables", "pie crust", "cream", "herbs", "broth"],
    difficulty: "Medium",
    cookTime: 50,
    category: "American",
    description: "Comfort food chicken pie",
  },
  {
    name: "Shrimp Scampi",
    ingredients: ["shrimp", "garlic", "white wine", "lemon", "butter", "pasta"],
    difficulty: "Medium",
    cookTime: 20,
    category: "Italian",
    description: "Garlic butter shrimp with pasta",
  },
  {
    name: "Chicken Shawarma",
    ingredients: ["chicken", "yogurt", "spices", "pita", "cucumber", "tahini"],
    difficulty: "Medium",
    cookTime: 30,
    category: "Middle Eastern",
    description: "Spiced chicken with Middle Eastern flavors",
  },
  {
    name: "Beef Tacos al Pastor",
    ingredients: ["beef", "pineapple", "chili", "onion", "cilantro", "tortillas"],
    difficulty: "Medium",
    cookTime: 25,
    category: "Mexican",
    description: "Mexican-style marinated beef tacos",
  },
  {
    name: "Chicken Satay",
    ingredients: ["chicken", "coconut milk", "curry powder", "peanut sauce", "skewers", "lime"],
    difficulty: "Medium",
    cookTime: 25,
    category: "Thai",
    description: "Grilled chicken skewers with peanut sauce",
  },
  {
    name: "Pork Carnitas",
    ingredients: ["pork shoulder", "orange", "lime", "cumin", "oregano", "garlic"],
    difficulty: "Medium",
    cookTime: 180,
    category: "Mexican",
    description: "Slow-cooked Mexican pulled pork",
  },
  {
    name: "Chicken Biryani",
    ingredients: ["chicken", "basmati rice", "yogurt", "spices", "onions", "saffron"],
    difficulty: "Medium",
    cookTime: 60,
    category: "Indian",
    description: "Fragrant spiced rice with chicken",
  },
  {
    name: "Fish Curry",
    ingredients: ["fish", "coconut milk", "curry leaves", "tamarind", "spices", "onion"],
    difficulty: "Medium",
    cookTime: 30,
    category: "Indian",
    description: "South Indian fish curry",
  },
  {
    name: "Chicken Adobo",
    ingredients: ["chicken", "soy sauce", "vinegar", "garlic", "bay leaves", "peppercorns"],
    difficulty: "Medium",
    cookTime: 40,
    category: "Filipino",
    description: "Filipino braised chicken",
  },
  {
    name: "Beef Bulgogi",
    ingredients: ["beef", "soy sauce", "pear", "garlic", "sesame oil", "ginger"],
    difficulty: "Medium",
    cookTime: 20,
    category: "Korean",
    description: "Korean marinated beef",
  },

  // Hard Recipes (35 recipes)
  {
    name: "Beef Wellington",
    ingredients: ["beef tenderloin", "puff pastry", "mushrooms", "herbs", "egg", "foie gras"],
    difficulty: "Hard",
    cookTime: 60,
    category: "British",
    description: "Beef wrapped in pastry with mushroom duxelles",
  },
  {
    name: "Chocolate Soufflé",
    ingredients: ["chocolate", "eggs", "butter", "sugar", "cream", "vanilla"],
    difficulty: "Hard",
    cookTime: 45,
    category: "French",
    description: "Light and airy chocolate dessert",
  },
  {
    name: "Duck Confit",
    ingredients: ["duck legs", "duck fat", "garlic", "thyme", "salt", "bay leaves"],
    difficulty: "Hard",
    cookTime: 240,
    category: "French",
    description: "Slow-cooked duck in its own fat",
  },
  {
    name: "Lobster Thermidor",
    ingredients: ["lobster", "cream", "egg yolks", "cognac", "mustard", "cheese"],
    difficulty: "Hard",
    cookTime: 45,
    category: "French",
    description: "Luxurious lobster in cream sauce",
  },
  {
    name: "Coq au Vin",
    ingredients: ["chicken", "red wine", "bacon", "mushrooms", "onions", "herbs"],
    difficulty: "Hard",
    cookTime: 90,
    category: "French",
    description: "Chicken braised in wine",
  },
  {
    name: "Osso Buco",
    ingredients: ["veal shanks", "white wine", "tomatoes", "carrots", "celery", "gremolata"],
    difficulty: "Hard",
    cookTime: 150,
    category: "Italian",
    description: "Braised veal shanks with vegetables",
  },
  {
    name: "Bouillabaisse",
    ingredients: ["fish", "shellfish", "saffron", "fennel", "tomatoes", "rouille"],
    difficulty: "Hard",
    cookTime: 60,
    category: "French",
    description: "Provençal fish stew",
  },
  {
    name: "Peking Duck",
    ingredients: ["duck", "hoisin sauce", "pancakes", "cucumber", "scallions", "five spice"],
    difficulty: "Hard",
    cookTime: 180,
    category: "Chinese",
    description: "Crispy skin duck with pancakes",
  },
  {
    name: "Paella Valenciana",
    ingredients: ["rice", "chicken", "rabbit", "beans", "saffron", "paprika"],
    difficulty: "Hard",
    cookTime: 45,
    category: "Spanish",
    description: "Traditional Spanish rice dish",
  },
  {
    name: "Beef Bourguignon",
    ingredients: ["beef chuck", "burgundy wine", "pearl onions", "mushrooms", "bacon", "herbs"],
    difficulty: "Hard",
    cookTime: 180,
    category: "French",
    description: "Classic French braised beef",
  },
  {
    name: "Ratatouille",
    ingredients: ["eggplant", "zucchini", "tomatoes", "peppers", "onions", "herbs"],
    difficulty: "Hard",
    cookTime: 90,
    category: "French",
    description: "Provençal vegetable stew",
  },
  {
    name: "Lamb Tagine",
    ingredients: ["lamb", "apricots", "almonds", "cinnamon", "ginger", "preserved lemons"],
    difficulty: "Hard",
    cookTime: 120,
    category: "Moroccan",
    description: "Slow-cooked Moroccan stew",
  },
  {
    name: "Cioppino",
    ingredients: ["fish", "crab", "shrimp", "mussels", "tomatoes", "wine"],
    difficulty: "Hard",
    cookTime: 60,
    category: "Italian-American",
    description: "San Francisco seafood stew",
  },
  {
    name: "Cassoulet",
    ingredients: ["white beans", "duck", "sausage", "pork", "herbs", "breadcrumbs"],
    difficulty: "Hard",
    cookTime: 240,
    category: "French",
    description: "Slow-cooked bean and meat casserole",
  },
  {
    name: "Chicken Kiev",
    ingredients: ["chicken breast", "butter", "herbs", "breadcrumbs", "eggs", "flour"],
    difficulty: "Hard",
    cookTime: 30,
    category: "Ukrainian",
    description: "Stuffed chicken with herb butter",
  },
  {
    name: "Risotto Milanese",
    ingredients: ["arborio rice", "saffron", "white wine", "parmesan", "bone marrow", "onion"],
    difficulty: "Hard",
    cookTime: 30,
    category: "Italian",
    description: "Creamy saffron risotto",
  },
  {
    name: "Beef Stroganoff",
    ingredients: ["beef tenderloin", "mushrooms", "sour cream", "cognac", "mustard", "onions"],
    difficulty: "Hard",
    cookTime: 45,
    category: "Russian",
    description: "Elegant beef in cream sauce",
  },
  {
    name: "Chicken Mole",
    ingredients: ["chicken", "chocolate", "chiles", "nuts", "spices", "tomatoes"],
    difficulty: "Hard",
    cookTime: 120,
    category: "Mexican",
    description: "Complex sauce with chocolate and chiles",
  },
  {
    name: "Seafood Paella",
    ingredients: ["rice", "shrimp", "mussels", "clams", "squid", "saffron"],
    difficulty: "Hard",
    cookTime: 45,
    category: "Spanish",
    description: "Seafood version of Spanish paella",
  },
  {
    name: "Rack of Lamb",
    ingredients: ["lamb rack", "herbs", "mustard", "breadcrumbs", "garlic", "wine"],
    difficulty: "Hard",
    cookTime: 35,
    category: "French",
    description: "Herb-crusted lamb rack",
  },
  {
    name: "Lobster Bisque",
    ingredients: ["lobster", "cream", "cognac", "tomato paste", "herbs", "stock"],
    difficulty: "Hard",
    cookTime: 90,
    category: "French",
    description: "Rich and creamy lobster soup",
  },
  {
    name: "Chicken Ballotine",
    ingredients: ["chicken", "stuffing", "herbs", "vegetables", "wine", "stock"],
    difficulty: "Hard",
    cookTime: 90,
    category: "French",
    description: "Deboned stuffed chicken",
  },
  {
    name: "Fish en Papillote",
    ingredients: ["fish", "vegetables", "herbs", "white wine", "parchment", "butter"],
    difficulty: "Hard",
    cookTime: 25,
    category: "French",
    description: "Fish cooked in parchment packets",
  },
  {
    name: "Beef Tenderloin",
    ingredients: ["beef tenderloin", "mushrooms", "shallots", "wine", "cream", "herbs"],
    difficulty: "Hard",
    cookTime: 45,
    category: "French",
    description: "Elegant beef with mushroom sauce",
  },
  {
    name: "Chicken Galantine",
    ingredients: ["chicken", "forcemeat", "pistachios", "herbs", "aspic", "vegetables"],
    difficulty: "Hard",
    cookTime: 120,
    category: "French",
    description: "Deboned stuffed chicken in aspic",
  },
  {
    name: "Veal Oscar",
    ingredients: ["veal", "crab", "asparagus", "hollandaise", "white wine", "butter"],
    difficulty: "Hard",
    cookTime: 30,
    category: "French",
    description: "Veal topped with crab and hollandaise",
  },
  {
    name: "Duck à l'Orange",
    ingredients: ["duck", "orange", "grand marnier", "stock", "honey", "vinegar"],
    difficulty: "Hard",
    cookTime: 120,
    category: "French",
    description: "Roasted duck with orange sauce",
  },
  {
    name: "Beef Roulade",
    ingredients: ["beef", "stuffing", "vegetables", "wine", "stock", "herbs"],
    difficulty: "Hard",
    cookTime: 90,
    category: "German",
    description: "Rolled stuffed beef",
  },
  {
    name: "Chicken Cordon Bleu",
    ingredients: ["chicken", "ham", "gruyere", "breadcrumbs", "eggs", "flour"],
    difficulty: "Hard",
    cookTime: 35,
    category: "French",
    description: "Stuffed and breaded chicken",
  },
  {
    name: "Salmon Wellington",
    ingredients: ["salmon", "puff pastry", "spinach", "mushrooms", "herbs", "egg"],
    difficulty: "Hard",
    cookTime: 40,
    category: "British",
    description: "Salmon wrapped in pastry",
  },
  {
    name: "Chicken Roulade",
    ingredients: ["chicken breast", "stuffing", "herbs", "vegetables", "wine", "cream"],
    difficulty: "Hard",
    cookTime: 45,
    category: "French",
    description: "Rolled stuffed chicken breast",
  },
  {
    name: "Beef Carpaccio",
    ingredients: ["beef tenderloin", "capers", "parmesan", "arugula", "lemon", "olive oil"],
    difficulty: "Hard",
    cookTime: 15,
    category: "Italian",
    description: "Thinly sliced raw beef",
  },
  {
    name: "Lobster Newburg",
    ingredients: ["lobster", "cream", "egg yolks", "sherry", "butter", "cayenne"],
    difficulty: "Hard",
    cookTime: 30,
    category: "American",
    description: "Rich lobster in cream sauce",
  },
  {
    name: "Chicken Chasseur",
    ingredients: ["chicken", "mushrooms", "tomatoes", "white wine", "herbs", "shallots"],
    difficulty: "Hard",
    cookTime: 60,
    category: "French",
    description: "Hunter-style chicken with mushrooms",
  },
  {
    name: "Veal Saltimbocca",
    ingredients: ["veal", "prosciutto", "sage", "white wine", "butter", "flour"],
    difficulty: "Hard",
    cookTime: 20,
    category: "Italian",
    description: "Veal with prosciutto and sage",
  },
]

export const allIngredients = [
  // Proteins
  "chicken",
  "beef",
  "pork",
  "lamb",
  "veal",
  "duck",
  "turkey",
  "fish",
  "salmon",
  "tuna",
  "shrimp",
  "lobster",
  "crab",
  "mussels",
  "clams",
  "squid",
  "eggs",
  "tofu",
  "beans",
  "lentils",
  "quinoa",

  // Vegetables
  "onion",
  "garlic",
  "tomato",
  "potato",
  "carrot",
  "celery",
  "bell pepper",
  "mushroom",
  "broccoli",
  "spinach",
  "lettuce",
  "cucumber",
  "zucchini",
  "eggplant",
  "asparagus",
  "corn",
  "peas",
  "cabbage",
  "cauliflower",
  "avocado",

  // Grains & Pasta
  "rice",
  "pasta",
  "noodles",
  "bread",
  "flour",
  "oats",
  "barley",
  "couscous",
  "bulgur",
  "farro",

  // Dairy
  "milk",
  "cream",
  "butter",
  "cheese",
  "mozzarella",
  "parmesan",
  "cheddar",
  "swiss",
  "feta",
  "ricotta",
  "yogurt",
  "sour cream",

  // Herbs & Spices
  "basil",
  "oregano",
  "thyme",
  "rosemary",
  "parsley",
  "cilantro",
  "mint",
  "sage",
  "dill",
  "chives",
  "paprika",
  "cumin",
  "coriander",
  "turmeric",
  "ginger",
  "cinnamon",
  "nutmeg",
  "cloves",
  "cardamom",
  "saffron",

  // Pantry Items
  "olive oil",
  "vegetable oil",
  "vinegar",
  "balsamic",
  "soy sauce",
  "honey",
  "sugar",
  "salt",
  "pepper",
  "mustard",
  "mayo",
  "ketchup",
  "hot sauce",
  "worcestershire",
  "vanilla",
  "lemon",
  "lime",
  "orange",

  // Nuts & Seeds
  "almonds",
  "walnuts",
  "pecans",
  "pine nuts",
  "peanuts",
  "cashews",
  "pistachios",
  "sesame seeds",
  "sunflower seeds",

  // Alcohol
  "white wine",
  "red wine",
  "beer",
  "cognac",
  "rum",
  "sherry",
  "marsala",
  "sake",
  "mirin",

  // Other
  "chocolate",
  "coconut milk",
  "stock",
  "broth",
  "capers",
  "olives",
  "anchovies",
  "pickles",
  "cranberries",
  "raisins",
  "dates",
  "apricots",
]
